module.exports = {
  currency: {
    name: "USD",
    symbol: "$",
    countryCode: "US",
    currencyCode: "$",
    isDefault: true,
  },
  _id: "692819754bd60f92c21474e9",
  privacyPolicyLink:
    '<h4>Privacy Policy for Quiet Chat</h4><h4><br></h4><h5>How We Use Your Information</h5><h6>Personal Information:</h6><p><span style="color: rgb(187, 187, 187);">We use your email address for account management and to communicate with you about updates or important information. </span></p><h6>Usage Data:</h6><p><span style="color: rgb(187, 187, 187); font-family: Helvetica, Arial, sans-serif; font-size: 13px; font-weight: 400;">We analyze usage patterns to improve our app\'s content and user experience. </span></p><h6>Device Information:</h6><p><span style="color: rgb(187, 187, 187);">We use device information for technical purposes, such as troubleshooting and ensuring compatibility.</span></p><h6>Information Sharing</h6><p><span style="color: rgb(187, 187, 187);">We do not sell, trade, or otherwise transfer your personally identifiable information to third parties. We may share aggregated and anonymized data for statistical purposes.</span></p><h6>Security</h6><p><span style="color: rgb(187, 187, 187);">We take reasonable measures to protect your personal information from unauthorized access or disclosure. However, no method of transmission over the Internet or electronic storage is completely secure. </span></p><h6>Your Choices</h6><p><span style="color: rgb(187, 187, 187);">You can manage your account settings and preferences within the app. You may opt out of promotional emails at any time by following the unsubscribe instructions in the email. </span></p><h6>Changes to This Privacy Policy</h6><p><span style="color: rgb(187, 187, 187);">We may update this Privacy Policy from time to time. Any changes will be posted on this page, and the "Last Updated" date will be revised accordingly. </span></p><h6>Contact Us</h6><ol><li><span style="color: rgb(187, 187, 187);">If you have any questions or concerns about this Privacy Policy, please contact us at [your contact email]. By using Wallki, you agree to the terms outlined in this Privacy Policy.</span></li></ol>',
  termsOfUsePolicyLink:
    '<h4>Terms and Condition for Quiet Chat</h4><h4><br></h4><h5>How We Use Your Information</h5><h6>Personal Information:</h6><p><span style="color: rgb(187, 187, 187);">We use your email address for account management and to communicate with you about updates or important information. </span></p><h6>Usage Data:</h6><p><span style="color: rgb(187, 187, 187);">We analyze usage patterns to improve our app\'s content and user experience. </span></p><h6>Device Information:</h6><p><span style="color: rgb(187, 187, 187);">We use device information for technical purposes, such as troubleshooting and ensuring compatibility.</span></p><h6>Information Sharing</h6><p><span style="color: rgb(187, 187, 187);">We do not sell, trade, or otherwise transfer your personally identifiable information to third parties. We may share aggregated and anonymized data for statistical purposes.</span></p><h6>Security</h6><p><span style="color: rgb(187, 187, 187);">We take reasonable measures to protect your personal information from unauthorized access or disclosure. However, no method of transmission over the Internet or electronic storage is completely secure. </span></p><h6>Your Choices</h6><p><span style="color: rgb(187, 187, 187);">You can manage your account settings and preferences within the app. You may opt out of promotional emails at any time by following the unsubscribe instructions in the email. </span></p><h6>Contact Us</h6><ol><li><span style="color: rgb(187, 187, 187);">If you have any questions or concerns about this Privacy Policy, please contact us at [your contact email]. By using Wallki, you agree to the terms outlined in this Privacy Policy.</span></li></ol><p><br></p>',
  googlePlayEnabled: false,
  stripeEnabled: true,
  stripePublishableKey: "pk_test_51PnZpxCgbHHJtm7RPVLjX28kr3mQGhHobJ1WaCGKBNh9cWZKLJJdu5f1EltNyjNVzcdQSYgJfizsbbC2RP987rTE00pdwG8KyZ",
  stripeSecretKey: "sk_test_51PnZpxCgbHHJtm7RDtzCYMoBhYZRAzexHtTEEhQW3AWcZkxMIoDiRq5gv9IaLrgkhUOoJN0oqpA86S7LTpCo47Sy00in4p6AjQ",
  razorpayEnabled: true,
  razorpayId: "RAZOR PAY ID",
  razorpaySecretKey: "rzp_test_SjZz9HC7RGCfCb",
  flutterwaveEnabled: true,
  flutterwaveId: "FLWPUBK_TEST-cdc51a4df113a91fe33a914eaf8d1c75-X",
  loginBonus: 5500,
  isDemoData: true,
  minCoinsToConvert: 1000,
  minCoinsForUserPayout: 1,
  minCoinsForHostPayout: 100,
  minCoinsForAgencyPayout: 10,
  maxFreeChatMessages: 1,
  privateKey: {
    type: "service_account",
    project_id: "quiet-chat-e419b",
    private_key_id: "b105426143426531402140ea9bf1645242cf68fc",
    private_key:
      "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDwoyxa98kBal4v\nBRnMAc6VeodiUR7k9VpyIqslPd1w9v81mSiU3N+9JgZ56Us6k7fmybivVTgD+F3I\n3GsjFps6XOTZXfzQDfV8NrQfbV1RZuidpbwGvLeemYoDIiJJePM9p96383/skC4z\nCW2S1NSI/fUphGIr2Q2cynLeG4XrD/puhU2NEw9dGajLfRFiQGfFILFC4abG3Yi0\nm88Xb2O62eSTGjedQUVTGd6i2qI0nKSu6ZwH1ax+bW6h7XQppak38tCMvI8bN2CE\nnnBtZYy9TKeR+VXNaZ3UTcH9/spo7MfBixjYLDRkV2NWGW043OuGj0FubAhsR7oF\nxjLF+FVXAgMBAAECggEAGo9QCnxV5b+ZRKRR/Bfo9suu3LWqbMf94yIbdMFWyyyf\n74kHlyKn2Uc0qMkMohsCzcjPBx8nTxzfMRfPBXDt0ivFoI5EpKwdv8eD6wIVrjHn\nE9tinPXAaJN2zbC7SxO7+T6pkPEh2fjx+HUecHnoOXSaVipD8aYD4B3iPsyX4+FJ\nTZkoO0uquVBsDgDrV46gYANjw/uHUarw2VqorJEgs0rbDegX1oRt/p4bWyAAB9Pr\nmLjeQkVLMx7O4O0yIXjoq3VtnBY8VhjsWRNgyY19Oc4sS7z/F+qMcZTQXE8/gMil\n0DG+bE9tAThPlnZw36e4jR78sCCOvR2AQGJvPm/6HQKBgQD782nb9TF+uQJia7m/\nOGjuXozTEKAXNQuHICu8CLayUiuqsboQipoRQtbNfDWS4/XpA6n0kPn8QXts5lMr\nhaxeFDhOEmNYfRZaVGK6fc6cU9KtKwzpVZSlI8oEQEnXRgN4ETzQZFhLttGfgPOM\n0KXIXPKzSOY7Q+l9sBYXpCjYSwKBgQD0gTaqU5kVciq6Ecw6K1RIWA7XZ+FtsY6I\naJ+jiGcAWeKcK1Zbv5BFCCLcupVyamZgnu8R3LGOfvL2XTHg6+wNYxw0LNABblwc\nd446uZdNBQFcxi96SpRjVdoLPiLzhkidkmqJ2lfDotdLcNlijb57hYCsixX4jvm6\n8x4huCSnpQKBgGdpIhLw0Y7UuuDQnF2a9p6X2i8rTLoZwJCGqMy1ut74EQovhlIR\nwWjCSU3v5EFVJXKtWU2TT7e03Mb2xj4/0F6Q6AdLTtFcDhenORqYVnwdf4Qp/lOr\nF6asSNdz15rvFq9qS86w0PjKocFY+R3b6Z+SXt8tVaoPlr9KzdaIP2d/AoGBANdp\ne8rmKgnN8rzJ718US4YNJs46dE5bT1L4siS2iOCzUEX8nHHqvOVEvMoxDHeoLBhW\nDhRzlm8Pg2jwRIB/+hD1T6TcEkoge8CMyF8OobE2hrPA25VnXYKC4b5j+REKLrG8\njGZ1Wjs/HWUWwD7m2Hok7W+Wfj3lYTmG9fYJMSoNAoGBANUSBp8I6tHXpBZG1kc+\nPD9Y/UqBUA5wAREgImjZ/WSZZ0N/V2MdilXSDSjBNwfWVwscfx5IFK25uXsJ0cYn\nfiFgNmhL3UZz08iyrRPEH7Rth7kGT7yv+7qZI3PjQ2gI9JD6shlYuigtvEoUboq2\nULb++O+fgqCAOVdNTunZgF+0\n-----END PRIVATE KEY-----\n",
    client_email: "firebase-adminsdk-fbsvc@quiet-chat-e419b.iam.gserviceaccount.com",
    client_id: "118162106097706648632",
    auth_uri: "https://accounts.google.com/o/oauth2/auth",
    token_uri: "https://oauth2.googleapis.com/token",
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40quiet-chat-e419b.iam.gserviceaccount.com",
    universe_domain: "googleapis.com",
  },
  createdAt: "2025-03-17T09:22:56.775Z",
  updatedAt: "2025-06-20T09:28:01.028Z",
  adminCommissionRate: 10,
  agoraAppCertificate: "agoraAppCertificate",
  agoraAppId: "agoraAppId",
  audioPrivateCallRate: 35,
  chatInteractionRate: 15,
  femaleRandomCallRate: 25,
  generalRandomCallRate: 10,
  isAppEnabled: true,
  // Force-update & store config
  androidMinVersionCode: 18,
  androidLatestVersionCode: 18,
  androidUpdateUrl: "https://play.google.com/store/apps/details?id=com.quietchat.video.live",
  iosMinVersionCode: 0,
  iosLatestVersionCode: 0,
  iosUpdateUrl: "",
  maleRandomCallRate: 15,
  videoPrivateCallRate: 45,
  callInitiatedAt: 10,
  messageInitiatedAt: 30,
  isAutoRefreshEnabled: false,
};
